version: '3.8'
services:

  nginx:
    build: .
    container_name: nginx
    ports:
      - "80:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - myapp-network

networks:
  myapp-network:
    driver: bridge